### ISSUE TITLE
macOS 10.14 isn't on PyPI

### ISSUE THREAD

**Issue by michael-jan** [DBraun/DawDreamer#127]
Is it possible to enable pip installation on macOS 10.14 Mojave?

**Comment by DBraun** [comment]
Sorry I've got bad news. Because I rely on GitHub actions it's hard to support older operating sytems. In fact, I've had to move on to macOS 11.0. I'll try to keep that as the minimum for as long as I can, but I don't think I'll be able to get 10.14 on PyPI. You could tinker with building for 10.14 locally if you do the following:
* In the Projucer, for the macOS builds, remove the `BUILD_DAWDREAMER_FAUST` preprocessor. (Faust requires version 11.0)
* In the Projucer, set the minimum macOS version to 10.14
* Follow the rest of the developer instructions in the Developer's Guide wiki (to be updated this week....)
