### ISSUE TITLE
Can't download dawdreamer with Python 3.13

### ISSUE THREAD

**Issue by Byter64** [DBraun/DawDreamer#209]
I wanted to download dawdreamer but were not able to do so. From Pypi it tells me that there was no version available, while from github it tells me that the file "dawdreamer.dll" is missing.

Systeminfo:
- Windows 11, 64 Bit
- Using anaconda
- Tested in new virtual environment with python 3.13.1

I tried to download from pypi with "pip install dawdreamer":
![image](https://github.com/user-attachments/assets/86596796-5f40-4859-8adb-878ced1f2fe5)

I tried to download from github with "pip install git+https://github.com/DBraun/DawDreamer.git@v0.8.3":
![image](https://github.com/user-attachments/assets/6365608e-8dd0-4e5d-bbc3-0848c8970d29)

**Comment by DBraun** [comment]
I think Python 3.13 isn't supported. You may be able to download a specific 3.12 wheel from https://pypi.org/project/dawdreamer/#history and install it in your 3.13 env, or you could use a Python 3.10-3.12 env. Python 3.9 and lower aren't in the latest release in order to keep the amount of data on pypi small (there's a limit)

**Comment by Byter64** [comment]
Yes, you are right. I totally forgot that 3.13 is the newest version now and thereby the default for new environments. Is there going to be support soon for 3.12?

**Comment by DBraun** [comment]
I'll try to include 3.13 in the next release but I'm not sure when that will be.

**Comment by Byter64** [comment]
Great :)
I will close this issue, as it has more or less been solved
