### ISSUE TITLE
Opening and showing UI of VSTs

### ISSUE THREAD

**Issue by ghost** [DBraun/DawDreamer#24]
Would it be possible to open the UI of VSTs?
Main reason is to automate some tasks via image recognition and automated mouse clicking.

For example looping over presets is in most plugins not supported and has to be done manually (look for button and click on).

PS: The project I was looking for 2 years. Played around with renderman but did not find the time to extend it.

**Comment by DBraun** [comment]
Good suggestion because some things just can't be modified via code such as drawing an ADSR curve, or changing a modular synth routing. As a starting point I would suggest we look at https://forum.juce.com/t/does-plugin-hosting-support-plugin-gui-as-a-component-child/16938/2 and seeing how Python can open viewers, kind of like opencv `cv2.imshow()`

**Comment by DBraun** [comment]
0.6.2 now has `open_editor()` for Plugin Processor. See `tests/test_plugins.py`
