### ISSUE TITLE
Issue with pip install on Windows

### ISSUE THREAD

**Issue by zzZeXo** [DBraun/DawDreamer#48]
I am in the Windows 10 console.
And when I try to install it via pip it returns

```
ERROR: Could not find a version that satisfies the requirement dawdreamer (from versions: none)
ERROR: No matching distribution found for dawdreamer
```

**Comment by DBraun** [comment]
Hi, sorry for seeing this late. What is your version of Python? Run `pip --version`. Maybe it's not 3.8 or 3.9? Sorry for that being the requirement in the moment, and it's not clear in the documentation.

**Comment by DBraun** [comment]
You can also try a specific wheel here: https://pypi.org/project/dawdreamer/#files

**Comment by zzZeXo** [comment]
Thank you, it solved my problem

I'm using Python 3.9.0

**Comment by zzZeXo** [comment]
Is it possible to load plugins in real time with GUI?

**Comment by zzZeXo** [comment]
I want to make a script that takes the mic input and reduces the background noise

**Comment by DBraun** [comment]
Great! So you installed by downloading a specific wheel because a plain pip install didn’t work?

Those features would be good, but they’re not implemented. You can subscribe to notifications here (real-time audio) https://github.com/DBraun/DawDreamer/issues/50
And (GUI)
https://github.com/DBraun/DawDreamer/issues/24
