### ISSUE TITLE
engine.set_bpm(123.45) should affect MIDI timing

### ISSUE THREAD

**Issue by kyungyunlee** [DBraun/DawDreamer#89]
Hi, thanks for the great library! 

While trying to confirm that DawDreamer renders MIDI exactly the same as when rendering with Reaper (or any DAW), I found that DawDreamer renders at a slower tempo. Any idea why this is happening?  

I am rendering using Addictive keys with a preset I saved. 

```
  engine = daw.RenderEngine(SAMPLE_RATE, BUFFER_SIZE)
  synth = engine.make_plugin_processor("my_synth", vst)
  assert synth.get_name() == "my_synth"

  if ".vst3" in vst:
      assert synth.load_vst3_preset(vst_preset_path)
  else:
      assert synth.load_preset(vst_preset_path)

  assert synth.load_midi(midi_path)
  
  time.sleep(0.5)

  graph = [
      (synth, []),
  ]
  engine.load_graph(graph)

  engine.render(duration)  
  audio = engine.get_audio()  # Returns array shaped (2, NUM_SAMPLES)

  sf.write(output_wav_path, audio.transpose(), SAMPLE_RATE)
```

<img width="1066" alt="Screen Shot 2022-04-28 at 11 10 11 AM" src="https://user-images.githubusercontent.com/19829532/165662366-30b190ca-2ab6-4581-93e0-068ecd364689.png">

**Comment by DBraun** [comment]
Taking a slight guess here. The MIDI file contains BPM information at [PPQ](https://en.wikipedia.org/wiki/Pulses_per_quarter_note)-rate. Right now `load_midi` converts this to seconds and places the notes on the timeline. Then `engine.set_bpm(90.)` or anything else will actually have no effect. I would want to improve this in the future so that you can change the BPM after loading a MIDI file (BPM does affect plugins and PlaybackWarpProcessor). But long story short, my guess is that the BPM of the MIDI file is not what Reaper is set to.

**Comment by kyungyunlee** [comment]
@DBraun Oops, I think it's a Reaper thing...Works fine with Logic Pro! Thanks for the quick comment.

**Comment by DBraun** [comment]
New features in 0.6.6 fix this!

**Comment by DBraun** [comment]
@cloudspins it's certainly lacking in several features like time signatures other than 4/4 and some kinds of MIDI events.

However, `load_midi` and `add_midi_note` both have a kwarg `beats=False`. If you set it to `True`, then the MIDI is loaded in relative to quarter notes, and so `engine.set_bpm` *will* have an effect on the output audio. Then you also have a choice of calling `engine.render(4.0, beats=True)`, which will render 4 beats according to the BPM instead of 4 seconds.

**Comment by cloudspins** [comment]
Hey Dan,

I really like the DawDreamer API, it's very elegant. The features would really help in developing a new DAW.
Can I pass a timeline with varying tempos and time signatures with continuous rendering? Does DawDreamer pass midi timecode and midi transport controls to the plugins?

What I'm developing is a DAW for Dolby Atmos and Eclipsa Audio (Google), and found there was no timeline in DawDreamer, which is really wanted when building a DAW. The immersive aspects are included as hard-coded immersive audio VST's, and so they need to receive the right timelines 24fps etc. The rendering is also done by the VST's but DawDreamer handles the graph.

The DAW does realtime "playback" with another API, and "rendering" with DawDreamer, the interface is build on an OpenGL based GUI engine.
Since this is a first step I'm not sure it's going to succeed, but DawDreamer is closest to API which could theoretically succeed.
May 12, 2025, 22:14 by ***@***.***:

**Comment by cloudspins** [comment]
Is the Playback Position (Midi Timecode) passed to the plugin graph?
Does DawDreamer PluginProcessor have multichannel i/o even when audio card is stereo or does the audio card limit the outputs of the PluginProcessor?
i.e. when I have a plugin, does it receive only the BPM or also the "playback position"?

This is crucial, because some immersive audio VST plugins require both BPM, and "playback position" and midi.start messages otherwise they cannot render the audio, and because thr VST's are multichannel they have tomexpose all their available channels to VST receiving "3D panners" to "playback" and "render" effrctively.
https://en.m.wikipedia.org/wiki/MIDI_timecode
https://dirt.design/DawDreamer/_generate/dawdreamer.PluginProcessor.html#dawdreamer.PluginProcessor

As you can see I am attempting to accomplish a form of synchronization between multichannel i/o's of the VST plugins.
May 12, 2025, 22:14 by ***@***.***:
